version: '3.8'

services:
  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    

  web:
    build: .
    volumes:
      - .:/src
    ports:
      - 8080:8080
    environment:
      - PORT=8080