version: '3.8'

services:
  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  web:
    build: .
    volumes:
      - .:/src
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE=API
      - USERNAMEDB=postgres
      - PASSWORDDB=postgres
      - HOSTDB=web-db
      - PORTDB=5432
    depends_on:
      - web-db
