version: '3.3'

services:
  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  web:
    build: .
    volumes:
      - .:/src
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE=API
      - USERNAMEDB=postgres
      - PASSWORDDB=postgres
      - HOSTDB=web-db
      - PORTDB=5432
      - SECRETORPRIVATEKEY=6%J5HDD-x{.[@~#MrZ&xr7*A`yUj48
    depends_on:
      - web-db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    expose:
      - 80
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@healtsafe.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - web-db  
    networks:
      - default